### PR TITLE
2-Add Chrome Compatibility

### PR DESCRIPTION
**Pull request by mo-pat**
- add function that returns browser namespace depending on browser being used (chrome or browser); allow code to be ran on either browser (chrome or firefox)
- Chrome extension do not allow promise based approach to async methods. Therefore, had to convert browser.query.tabs method into callback to allow it to function on chrome
- remove try catch
- add reportError to sendProperties() & togglePatronus() since error catch is removed

### CODE REVIEW

**Review by EpithetUser — CHANGES_REQUESTED** [review]
...

**Review by JadeMaveric — CHANGES_REQUESTED** [review]
Everything looks good

Just add the change mentioned in #2.
Also, since it now works on both chrome and firefox, rename the folder to `extension` (using [`git mv`](https://git-scm.com/docs/git-mv))

**Comment by mo-pat** [comment]
Thanks! I made the changes:
- Rename firefox to extension directory
- Removed legacy event handler in html 

Let me know if there's anything else.

**Review by JadeMaveric — APPROVED** [review]
Everything look good. Great job!

**Pull request merged**
