### PR TITLE
Added tooltips

### LINKED ISSUE #6: Add tooltips to browser bar UI
I tried to make the UI as intuitive as possible, and did initially add tooltips to the input labels. But my CSS skills aren't the best, and it messed up the layout.

I suppose this should be something fairly simple to anyone with frontend experience. Either to fix the CSS, or switch to using the title attribute (and removing the unnecessary CSS)

A suitable PR would add tooltips to the `keywords` and `interval` label documenting what they do.

### PR DESCRIPTION
**Pull request by ameybh**
Used the `title` attribute since it was a cleaner look.
I think this is much easier to understand and modify.
Fixes #6

### CODE REVIEW

**Comment by ameybhavsar24** [comment]
Fixes #6

**Comment by ameybh** [comment]
Hey @JadeMaveric, can you review this?

**Comment by ameybh** [comment]
@JadeMaveric, just checking up. Can you merge?

**Review by JadeMaveric — APPROVED** [review]
Everything looks good. Sorry for the delay, not sure how this slipped past me.

**Pull request merged**
